import type { Dataset, Distribution } from "@/generated/prisma/client";

/**
 * Distribution row factory backed by the generated Prisma type so future schema
 * additions break fixtures at compile time instead of silently passing stale
 * shapes through to tests.
 */
export const mockDistribution = (
  overrides: Partial<Distribution> = {},
): Distribution => ({
  id: "dist-1",
  title: null,
  description: null,
  downloadURL: null,
  accessURL: null,
  mediaType: null,
  format: null,
  conformsTo: null,
  describedBy: null,
  fileName: null,
  filePath: null,
  fileSize: null,
  sortOrder: 0,
  originalPath: null,
  parquetPath: null,
  rowCount: null,
  profiledAt: null,
  profileStatus: "none",
  profileError: null,
  datasetId: "ds-1",
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  ...overrides,
});

export const mockDataset = (overrides: Partial<Dataset> = {}): Dataset => ({
  id: "ds-1",
  slug: "test-dataset",
  title: "Test Dataset",
  description: "A test dataset",
  modified: new Date("2026-01-01T00:00:00.000Z"),
  accessLevel: "public",
  identifier: "test-dataset-identifier",
  publisherId: "pub-1",
  contactName: null,
  contactEmail: null,
  bureauCode: null,
  programCode: null,
  license: null,
  rights: null,
  spatial: null,
  temporal: null,
  issued: null,
  accrualPeriodicity: null,
  conformsTo: null,
  dataQuality: null,
  describedBy: null,
  isPartOf: null,
  landingPage: null,
  language: null,
  primaryITInvestmentUII: null,
  references: null,
  systemOfRecords: null,
  status: "published",
  createdById: null,
  createdAt: new Date("2026-01-01T00:00:00.000Z"),
  updatedAt: new Date("2026-01-01T00:00:00.000Z"),
  workflowStatus: "draft",
  reviewerId: null,
  reviewNote: null,
  submittedAt: null,
  reviewedAt: null,
  publishedAt: null,
  version: null,
  versionNotes: null,
  seriesId: null,
  previousVersion: null,
  harvestSourceId: null,
  harvestIdentifier: null,
  deletedAt: null,
  ...overrides,
});
